project:
  type: book
  output-dir: docs
  preview:
    port: 4300

engine: knitr

book:
  sidebar:
    search: true
    logo: assets/images/favicon.ico
    collapse-level: 1
    background: 'light'
  title: "Data Reporting"
  subtitle: "Cronkite School MAIJ Program, Spring 2024"
  page-navigation: true

  page-footer:
     background: "#096b72"
     left: |
       Data reporting for investigative journalism, Spring 2024,  written by Sarah Cohen
     right: |
       Produced with <a href="https://quarto.org">Quarto</a>

  favicon: assets/images/favicon.ico
  site-url: https://cronkitedata.github.io/djtextbook/
  repo-url: https://github.com/cronkitedata/djtextbook

  chapters:
    - index.qmd

    - part: start.qmd
      chapters:
        - start-story.qmd
        - start-data-def.qmd
        - start-data-document.qmd
        - start-hunt.qmd
        - start-build-own.qmd

    - part: quickstart.qmd
      chapters:
        - r-install.qmd
        - appendix-program.qmd
        - r-start.qmd
        - r-quarto.qmd
        - r-data-import.qmd
        - r-verbs.qmd

    - part: rdepth.qmd
      chapters:
         - start-tidy.qmd
         - r-verb-filter.qmd
         - r-verb-mutate.qmd
         - r-verb-groupby.qmd
         - r-verb-join.qmd
         - advanced-regex.qmd
         - advanced-regex-r.qmd
         - r-recipes.qmd

    - part: vis.qmd
      chapters:
         - vis-reporting.qmd
         - vis-tables.qmd
         - vis-demo.qmd
         - vis-practice.qmd
         - vis-maps-begin.qmd
         - vis-maps-firstmap.qmd

    - part: advanced.qmd
      chapters:
         - advanced-pdf.qmd
         - advanced-openrefine.qmd
         - advanced-scrape1.qmd
         - advanced-scrape2.qmd
#
  appendices:
   - appendix-math.qmd
   - appendix-filetypes.qmd
   - appendix-ppp.qmd
#
format:
  html:
    theme:
      - cosmo
      - custom.scss
    highlight-style: printing
    code-overflow: wrap
    code-block-bg: true
    code-block-border-left: true
    code-copy: true
    number-depth: 2
    default-image-extension: png
    df-print: paged
    page-layout: full
    toc: true
    toc-location: right
    toc-title: "In this chapter:"
    grid:
      margin-width: 10%;
      sidebar-width: 20%;


execute:
     echo: true
     warning: false
     message: false
     freeze: auto

knitr: true

