# (PART) Spreadsheets { .unnumbered}


# Introduction { #xl-intro .unnumbered}

Some people consider using spreasheets the table stakes for getting into data journalism. It's relatively easy to see what you're doing and you can easily share your work with your colleagues. In fact,  pieces of the [Pulitzer-Prize winning COVID-19 coverage](https://www.pulitzer.org/winners/new-york-times-6) from The New York Times was compiled using an elaborate and highly tuned set of Google spreadsheets with dozens of contributors. 

This guide uses Excel for the Mac from Office 365, which most newsrooms still have. The reason is that they're a little easier to get around and in particular have more options for pivot tables -- a crucial part of the table stakes. But Google sheets shine elsewhere in this book, particularly when it comes time to scrape websites or import non-tabular file formats like JSON. 

Excel in Windows is very different -- it has much more capability for working with large and more complex data, and provides better tuning for import and other operations.  

Most of the screen shots and instructions are created with a MacOS Monterey. Some come from earlier Mac versions, but are largely the same now. Windows users should replace any instructions for using the CMD- key with the CTL- key.  There is a table that compares keystrokes for Apple desktops, laptops and Windows machines for Excel at the bottom of [An Excel Refresher](xl-refresher)


## Tutorials {-}

Spreadsheets in the form of Excel or Google Sheets are used in almost every workplace in America. This section covers most of what you need in the newsroom, which is a different set of skills than in other businesses. 

* [An Excel Refresher](xl-refresher.html) : Start over with good habits

* [Sorting and filtering to find stories](xl-filter-sort.html) : The first step of interviewing data

* [Grouping with pivot tables](xl-pivot.html): Aggregating, and the super power of spreadsheets

* [Formulas in Excel](xl-formulas.html): Percents, sums, and other basic computations used in newsrooms.

## Practice exercises {-}

* [Practice with "notice of claims" from Phoenix](xl-practice-noc.html): Filtering and pivot table practice using claims made against the city of Phoenix 2010-2020. 
